                  import { runtimeOsmConfig } from './osm-regions.js';

                  export const POINTS_PER_MILE = 10;
                  export const POINTS_PER_NEW_HISTORY_SITE = 25;
                  export const POINTS_PER_OBSERVATION = 15;
                  export const STREAK_BONUS_PER_DAY = 5;
                  export const MAX_GPS_ACCURACY_METERS = 50;
                  export const MAX_WALK_SPEED_MPS = 15;

                  export const CITIES = {
  arlington: {
    name: 'Arlington County', state: 'VA', center: { lat: 38.8783, lng: -77.1011 }, zoom: 12,
    dataFile: './regions/arlington-va/pois.json'
  },
  'falls-church': {
    name: 'Falls Church', state: 'VA', center: { lat: 38.8823, lng: -77.1711 }, zoom: 13,
    dataFile: './regions/falls-church-va/pois.json'
  },
  norfolk: {
    name: 'Norfolk',
    state: 'VA',
    center: { lat: 36.8508, lng: -76.2859 },
    zoom: 14,
    dataFile: './data/norfolk-poi.json',
    supplementalPoiFiles: ['./data/osm/norfolk-osm-poi.json'],
    civicFile: './regions/norfolk/civic/index.json', weatherFile: './regions/norfolk/weather.json'
  },
  newyork: {
    name: 'New York',
    state: 'NY',
    center: { lat: 40.73088, lng: -73.99759 },
    zoom: 13,
    dataFile: './data/newyork-poi.json',
    supplementalPoiFiles: ['./data/osm/newyork-osm-poi.json'],
    // Generated by this app's NYC package build. This is an app-owned static
    // artifact, not a Gremlin Lab runtime dependency.
    supplementalPoiFile: './regions/new-york-city/new-york-city-poi.json',
    civicFile: './regions/new-york-city/civic/index.json', weatherFile: './regions/new-york-city/weather.json'
  },
  philadelphia: {
    name: 'Philadelphia',
    state: 'PA',
    center: { lat: 39.9526, lng: -75.1652 },
    zoom: 13,
    dataFile: './data/philadelphia-poi.json',
    supplementalPoiFiles: ['./data/osm/philadelphia-osm-poi.json'],
    supplementalPoiFile: './regions/philadelphia/philadelphia-poi.json',
    civicFile: './regions/philadelphia/civic/index.json', weatherFile: './regions/philadelphia/weather.json'
  },
  richmond: {
    name: 'Richmond',
    state: 'VA',
    center: { lat: 37.5407, lng: -77.4360 },
    zoom: 13,
    dataFile: './data/richmond-poi.json',
    boundarySource: { name: 'City of Richmond Boundary', url: 'https://services1.arcgis.com/k3vhq11XkBNeeOfM/ArcGIS/rest/services/City_Boundary/FeatureServer/0' },
    supplementalPoiFiles: ['./data/osm/richmond-osm-poi.json'],
    supplementalPoiFile: './regions/richmond/richmond-poi.json',
    civicFile: './regions/richmond/civic/index.json', weatherFile: './regions/richmond/weather.json'
  },
  anchorage: {
    name: 'Anchorage', state: 'AK', center: { lat: 61.1085, lng: -149.4492 }, zoom: 9,
    dataFile: './data/anchorage-poi.json',
    boundarySource: { name: 'Municipality of Anchorage Boundary', url: 'https://services2.arcgis.com/Ce3DhLRthdwbHlfF/ArcGIS/rest/services/MOA_Boundary/FeatureServer/0' }
  },
  tempe: {
    name: 'Tempe', state: 'AZ', center: { lat: 33.3927, lng: -111.9279 }, zoom: 12,
    dataFile: './data/tempe-poi.json',
    boundarySource: { name: 'City of Tempe Boundary', url: 'https://services.arcgis.com/lQySeXwbBg53XWDi/ArcGIS/rest/services/City_Boundary/FeatureServer/0' }
  },
  'los-angeles': {
    name: 'Los Angeles', state: 'CA', center: { lat: 34.0522, lng: -118.4118 }, zoom: 10,
    dataFile: './data/los-angeles-poi.json',
    boundarySource: { name: 'Los Angeles City Boundary', url: 'https://services1.arcgis.com/tzwalEyxl2rpamKs/arcgis/rest/services/Los_Angeles_City_Boundary/FeatureServer/0' }
  },
  baltimore: {
    name: 'Baltimore', state: 'MD', center: { lat: 39.2847, lng: -76.6205 }, zoom: 11,
    dataFile: './data/baltimore-poi.json',
    boundarySource: { name: 'Baltimore City Boundary', url: 'https://services5.arcgis.com/U5lRs16ODaohcqOy/ArcGIS/rest/services/City_Boundary/FeatureServer/0' }
  },
  detroit: {
    name: 'Detroit', state: 'MI', center: { lat: 42.3527, lng: -83.0990 }, zoom: 11,
    dataFile: './data/detroit-poi.json',
    boundarySource: { name: 'City of Detroit Boundary', url: 'https://services2.arcgis.com/qvkbeam7Wirps6zC/ArcGIS/rest/services/City_of_Detroit_Boundary/FeatureServer/0' }
  },
  'corpus-christi': {
    name: 'Corpus Christi', state: 'TX', center: { lat: 27.6985, lng: -97.3617 }, zoom: 10,
    dataFile: './data/corpus-christi-poi.json',
    boundarySource: { name: 'Corpus Christi City Limits', url: 'https://services.arcgis.com/0J4ZNc4NaTguvRy0/ArcGIS/rest/services/OpenData/FeatureServer/36' }
  },
  'fort-worth': {
    name: 'Fort Worth', state: 'TX', center: { lat: 32.7998, lng: -97.3171 }, zoom: 10,
    dataFile: './data/fort-worth-poi.json',
    boundarySource: { name: 'Fort Worth Full Purpose City Limits', url: 'https://mapit.fortworthtexas.gov/ags/rest/services/Basemaps/Basemap/MapServer/112', where: "DESIGNATIO = 'Full Purpose'" }
  },
  seattle: {
    name: 'Seattle', state: 'WA', center: { lat: 47.6141, lng: -122.3352 }, zoom: 11,
    dataFile: './data/seattle-poi.json',
    boundarySource: { name: 'Seattle Area Polygon', url: 'https://services.arcgis.com/ZOyb2t4B0UYuYNYH/ArcGIS/rest/services/Seattle_Area_Polygon/FeatureServer/0' },
    civicFile: './regions/seattle/civic/index.json'
  },
  columbus: {
    name: 'Columbus', state: 'OH', center: { lat: 39.9829, lng: -82.9911 }, zoom: 10,
    dataFile: './data/columbus-poi.json',
    boundarySource: { name: 'Columbus Corporate Boundary', url: 'https://maps.columbus.gov/arcgis/rest/services/CityServices/KeyLayers/MapServer/2' }
  },
  pittsburgh: {
    name: 'Pittsburgh', state: 'PA', center: { lat: 40.4400, lng: -79.9850 }, zoom: 11,
    dataFile: './data/pittsburgh-poi.json',
    boundarySource: { name: 'City of Pittsburgh Boundary', url: 'https://services1.arcgis.com/YZCmUqbcsUpOKfj7/arcgis/rest/services/City_Boundary/FeatureServer/0' }
  },
  keystone: {
    name: 'Keystone & Summit County',
    state: 'CO',
    center: { lat: 39.605, lng: -105.946 },
    zoom: 11,
    dataFile: './data/keystone-colorado-poi.json',
    supplementalPoiFile: './regions/keystone-colorado/keystone-colorado-poi.json',
    civicFile: './regions/keystone-colorado/civic/index.json', weatherFile: './regions/keystone-colorado/weather.json',
    boundarySource: { name: 'U.S. Census Bureau Keystone census-designated place boundary', url: 'https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/Places_CouSub_ConCity_SubMCD/MapServer/5', where: "STATE = '08' AND BASENAME = 'Keystone'" }
  },
  pgcounty: {
    name: "Prince George's County",
    state: 'MD',
    center: { lat: 38.8315, lng: -76.8465 },
    zoom: 11,
    dataFile: './data/pgcounty-poi.json',
    civicFile: './regions/prince-georges-county/civic/index.json', weatherFile: './regions/prince-georges-county/weather.json'
  },
  fairfax: {
    name: 'Fairfax County',
    state: 'VA',
    center: { lat: 38.8462, lng: -77.3064 },
    zoom: 11,
    dataFile: './regions/fairfax-county-va/pois.json',
    journeyFile: './regions/fairfax-county-va/journeys.json',
    edgeFile: './regions/fairfax-county-va/edges.json',
    discoverFile: './regions/fairfax-county-va/discover.json',
    learnFile: './regions/fairfax-county-va/learn.json',
    capabilitiesFile: './regions/fairfax-county-va/capabilities.json',
    civicFile: './regions/fairfax-county-va/civic/index.json',
    packId: 'fairfax'
  },
  alexandria: {
    name: 'Alexandria',
    state: 'VA',
    center: { lat: 38.8048, lng: -77.0469 },
    zoom: 13,
    dataFile: './regions/alexandria-va/pois.json',
    civicFile: './regions/alexandria-va/civic/index.json'
  },
  loudoun: {
    name: 'Loudoun County',
    state: 'VA',
    center: { lat: 39.0768, lng: -77.6536 },
    zoom: 11,
    dataFile: './regions/loudoun-county-va/pois.json',
    journeyFile: './regions/loudoun-county-va/journeys.json',
    civicFile: './regions/loudoun-county-va/civic/index.json'
  },
  dc: {
    name: 'Washington',
    state: 'DC',
    center: { lat: 38.8951, lng: -77.0364 },
    zoom: 13,
    dataFile: './data/dc-poi.json',
    supplementalPoiFile: './regions/washington-dc/washington-dc-poi.json',
    neighborhoodFile: './regions/washington-dc/geography/neighborhoods.geojson',
    spatialIndexPath: './regions/washington-dc/spatial',
    geographySourceFile: './regions/washington-dc/geography/source.json',
    civicFile: './regions/washington-dc/civic/index.json',
    weatherFile: './regions/washington-dc/weather.json'
  },
  sedona: {
    name: 'Sedona',
    state: 'AZ',
    center: { lat: 34.8712, lng: -111.7904 },
    zoom: 13,
    dataFile: './data/sedona-arizona-poi.json',
    supplementalPoiFile: './regions/sedona-arizona/sedona-arizona-poi.json',
    civicFile: './regions/sedona-arizona/civic/index.json',
    weatherFile: './regions/sedona-arizona/weather.json',
    boundarySource: { name: 'U.S. Census Bureau Sedona incorporated place boundary', url: 'https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/Places_CouSub_ConCity_SubMCD/MapServer/4', where: "STATE = '04' AND BASENAME = 'Sedona'" }
  },
  boise: {
    name: 'Boise–Meridian–Old Town', state: 'ID', center: { lat: 43.599, lng: -116.252 }, zoom: 12,
    dataFile: './data/boise-meridian-idaho-poi.json', supplementalPoiFile: './regions/boise-meridian-idaho/boise-meridian-idaho-poi.json',
    civicFile: './regions/boise-meridian-idaho/civic/index.json', weatherFile: './regions/boise-meridian-idaho/weather.json',
    boundarySource: { name: 'Ada County City Limits — Boise', url: 'https://services1.arcgis.com/WHM6qC35aMtyAAlN/arcgis/rest/services/CityLimitsAndImpactAreas/FeatureServer/1', where: "CITY = 'Boise'" }
  },
  asheville: { name: 'Asheville', state: 'NC', center: { lat: 35.57, lng: -82.54 }, zoom: 11, dataFile: './regions/asheville/pois.json', civicFile: './regions/asheville/civic/index.json' },
  boston: { name: 'Boston', state: 'MA', center: { lat: 42.325, lng: -71.075 }, zoom: 11, dataFile: './regions/boston/pois.json', civicFile: './regions/boston/civic/index.json' },
  boulder: { name: 'Boulder', state: 'CO', center: { lat: 40.015, lng: -105.27 }, zoom: 11, dataFile: './regions/boulder/pois.json', civicFile: './regions/boulder/civic/index.json' },
  chicago: { name: 'Chicago', state: 'IL', center: { lat: 41.845, lng: -87.73 }, zoom: 10, dataFile: './regions/chicago/pois.json', civicFile: './regions/chicago/civic/index.json' },
  denver: { name: 'Denver', state: 'CO', center: { lat: 39.73, lng: -104.88 }, zoom: 10, dataFile: './regions/denver/pois.json', civicFile: './regions/denver/civic/index.json' },
  'new-orleans': { name: 'New Orleans', state: 'LA', center: { lat: 29.97, lng: -90.055 }, zoom: 11, dataFile: './regions/new-orleans/pois.json', civicFile: './regions/new-orleans/civic/index.json' },
  portland: { name: 'Portland', state: 'OR', center: { lat: 45.555, lng: -122.64 }, zoom: 10, dataFile: './regions/portland/pois.json', civicFile: './regions/portland/civic/index.json' },
  'portland-maine': { name: 'Portland', state: 'ME', center: { lat: 43.675, lng: -70.245 }, zoom: 11, dataFile: './regions/portland-maine/pois.json', civicFile: './regions/portland-maine/civic/index.json' },
  'san-francisco': { name: 'San Francisco', state: 'CA', center: { lat: 37.77, lng: -122.435 }, zoom: 11, dataFile: './regions/san-francisco/pois.json', civicFile: './regions/san-francisco/civic/index.json' },
  'santa-fe': { name: 'Santa Fe', state: 'NM', center: { lat: 35.665, lng: -105.96 }, zoom: 11, dataFile: './regions/santa-fe/pois.json', civicFile: './regions/santa-fe/civic/index.json' }
};
Object.entries(CITIES).forEach(([cityId, city]) => { city.osm = runtimeOsmConfig(cityId, city); });
                  export const DEFAULT_PROFILE = {
  id: 'local-user', totalPoints: 0, walksCompleted: 0, milesTotal: 0,
  sitesDiscovered: {}, visitedPoiIds: [], observationsLogged: 0, streakDays: 0, lastWalkDate: null
};
                  export const GEOFENCE_CATEGORIES = [
  ['library', '📚 Libraries'], ['park', '🌳 Parks'], ['public_art', '🎨 Public Art'],
  ['recreation_center', '🏢 Rec centers'], ['water_access', '🌊 Water access'],
  ['community_garden', '🌱 Community Gardens'], ['history', '✦ History Sites'],
  ['trail', '🥾 Trails'], ['wifi', '📶 Free Wi-Fi']
];
export const DEFAULT_SETTINGS = {
  id: 'app-settings', activeCity: null, lastSyncedAt: null, lastSupabaseHeartbeatAt: null,
  enableGeofencing: true, geofenceCategories: ['recreation', 'cuisine'], favoriteCategories: [], favoriteRegionIds: [], defaultGeofenceRadiusMeters: 50, defaultPinVisibility: 'private', shareAttribution: '', customObservationTags: {}, companionWalker: 'inky', onboardingCompleted: false, entitlements: { fieldEdition: false, cloudJournalBackup: false, offlineRegions: [], partnerGrants: [] }
};

export const OBSERVATION_ICONS = ['camera', 'tree', 'star', 'heart', 'coffee', 'book-open', 'music', 'wind'];

                  export const state = {
  map: null, userMarker: null, routeLine: null, draftMarker: null, currentPosition: null,
  activeWalk: null, watchId: null, timerId: null, prompted: new Set(), currentSite: null,
  draftObservationLocation: null, archiveFilter: 'all', activeView: 'map', modalOpen: null, activeCity: 'fairfax',
  profile: { ...DEFAULT_PROFILE }, settings: { ...DEFAULT_SETTINGS }, historyLayer: null, observationLayer: null, poiLayer: null, trailLayer: null,
  cityPois: {}, trailSegments: {}, poiTags: new Set(),
  online: { client: null, session: null, remoteProfile: null, candidate: null, leaderboard: [], incoming: [] }
};

                  export const el = (id) => document.getElementById(id);


export const POI_TAGS = [
  ['park', '🌳 Parks'], ['public_art', '🎨 Public Art'], ['recreation_center', '🏢 Rec centers'],
  ['water_access', '🌊 Water Access'], ['trail', '🥾 Trails'], ['library', '📚 Libraries'],
  ['community_garden', '🌱 Community Gardens'], ['history', '🏛 History Sites'],
  ['history_landmark', '🏛 Landmarks'], ['history_monument', '🗿 Monuments'], ['history_museum', '🖼 Museums'],
  ['history_cemetery', '🪦 Cemeteries'], ['history_marker', '📜 Historical Markers'],
  ['wifi', '📶 Free Wi-Fi'], ['osm', '🗺 OpenStreetMap places'], ['basketball', 'Basketball'], ['tennis', 'Tennis'],
  ['coffee', '☕ Coffee stops'],
  ['pantry', '🥫 Food access'], ['event', '📅 Events'], ['nature', '🌿 Nature'], ['community', '🏘 Community'], ['water', '💧 Water'], ['art', '🎨 Art'], ['wildlife', '🦉 Wildlife now'],
  ['playground', 'Playground'], ['dog_park', 'Dog park'], ['splash_pad', 'Splash pad'],
  ['disc_golf', 'Disc golf'], ['skate_park', 'Skate park'], ['restrooms', 'Restrooms']
];
                  export const TAG_LABELS = Object.fromEntries(POI_TAGS);
export const POI_TAG_PRIORITY = ['history', 'event', 'news', 'art', 'public_art', 'monument', 'marker', 'landmark', 'museum', 'cemetery', 'park', 'nature', 'garden', 'community_garden', 'playground', 'dog_park', 'shelter', 'water_access', 'drinking_water', 'water_fountain', 'water', 'wildlife', 'rest', 'restrooms', 'bench', 'trail', 'coffee', 'cafe', 'coffee_shop', 'market', 'farmers_market', 'grocery', 'supermarket', 'restaurant', 'fast_food', 'pantry', 'community', 'recreation_center', 'library', 'wifi'];
// Keep map symbols literal: Wi-Fi must never fall back to a navigation arrow.
export const POI_ICONS = { park: 'tree', nature: 'tree', garden: 'tree', community_garden: 'tree', playground: 'tree', dog_park: 'tree', shelter: 'tree', wildlife: 'eye', rest: 'building', restrooms: 'building', bench: 'bench', drinking_water: 'droplet', water_fountain: 'droplet', water: 'droplet', water_access: 'anchor', trail: 'walk', history: 'bookmark', monument: 'bookmark', marker: 'bookmark', landmark: 'building', museum: 'book-open', cemetery: 'map-pin', art: 'star', public_art: 'star', coffee: 'coffee', cafe: 'coffee', coffee_shop: 'coffee', market: 'utensils', farmers_market: 'utensils', grocery: 'utensils', supermarket: 'utensils', restaurant: 'utensils', fast_food: 'utensils', event: 'star', news: 'star', pantry: 'home', community: 'home', recreation_center: 'activity', library: 'book-open', wifi: 'wifi' };
// History sites are split into subtypes so the filter sheet isn't one catch-all
// "History" bucket — each gets its own chip and its own pin glyph.
                export const HISTORY_SUBTYPES = {
  landmark: { label: 'Landmarks', icon: 'building' },
  monument: { label: 'Monuments', icon: 'bookmark' },
  museum: { label: 'Museums', icon: 'book-open' },
  cemetery: { label: 'Cemeteries', icon: 'map-pin' },
  marker: { label: 'Historical Markers', icon: 'bookmark' } // default/fallback subtype
};
