const DATABASE_NAME = 'walk-wildlife-journal';
const DATABASE_VERSION = 20;
const STORES = ['walks','observations','moments','profile','settings','points_of_interest','poi_metadata','regions','region_pois','region_buckets','field_editions','civic_witnesses','neighborhood_discoveries','walk_drafts','walk_events','personal_places','personal_place_categories','layer_settings','voice_notes','journal_audio','county_additions','notification_state','spatial_local_operations','geo_cyphers','geo_cypher_keys','geo_cypher_events','saved_routes','biodiversity_preferences','geo_cypher_manifests','geo_cypher_audio','radio_manifests','radio_playback_state','radio_saved_tracks','radio_transition_assets','spatial_queries','rooms','radio_playlists','walk_soundtracks','outbox'];
const sessionId = globalThis.crypto?.randomUUID?.() || `session-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const memoryStores = new Map(); const listeners = new Set(); const transitions = [];
let database = null; let openPromise = null; let state = 'checking'; let transitionAt = performance.now?.() || Date.now();
const channel = typeof BroadcastChannel === 'function' ? new BroadcastChannel('walk-wildlife-journal-coordination') : null;
channel?.unref?.();
const memoryStore = (name) => { if (!memoryStores.has(name)) memoryStores.set(name, new Map()); return memoryStores.get(name); };
function transition(next, details = {}) { const now = performance.now?.() || Date.now(); const event = { state: next, databaseName: DATABASE_NAME, currentVersion: database?.version || 0, targetVersion: DATABASE_VERSION, elapsedMs: Math.round(now - transitionAt), reason: details.reason || null, tabSessionId: sessionId, error: details.error ? { name: details.error.name, message: details.error.message } : null, at: new Date().toISOString() }; transitionAt = now; state = next; transitions.push(event); if (transitions.length > 50) transitions.shift(); listeners.forEach((listener) => listener(event)); channel?.postMessage({ type: 'durability-state', event }); globalThis.dispatchEvent?.(new CustomEvent('persistence-state-changed', { detail: event })); }
function ensureStores(target) { for (const name of STORES) if (!target.objectStoreNames.contains(name)) target.createObjectStore(name, { keyPath: 'id' }); }
function result(request) { return new Promise((resolve, reject) => { request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
function whenComplete(tx) { return new Promise((resolve, reject) => { tx.oncomplete = resolve; tx.onerror = () => reject(tx.error); tx.onabort = () => reject(tx.error); }); }
function recordTime(value) { return Number(value?.updatedAt || value?.createdAt || 0); }
async function mergeMemory() { if (!database || !memoryStores.size) return; const candidates = []; for (const [name, records] of memoryStores) for (const record of records.values()) candidates.push({ name, record, durable: await get(name, record.id) }); const tx = database.transaction([...memoryStores.keys()], 'readwrite'); for (const { name, record, durable } of candidates) if (!durable || recordTime(record) >= recordTime(durable)) tx.objectStore(name).put(record); await whenComplete(tx); memoryStores.clear(); }
function attach(connection) { connection.onversionchange = () => { connection.close(); if (database === connection) database = null; transition('recovering', { reason: 'versionchange' }); }; connection.onclose = () => { if (database === connection) { database = null; transition('recovering', { reason: 'connection-closed' }); } }; return connection; }
async function open({ timeoutMs = 1500 } = {}) { if (database) return true; if (openPromise) return openPromise; openPromise = new Promise((resolve, reject) => { if (typeof indexedDB === 'undefined') { transition('temporary', { reason: 'indexeddb-unsupported' }); resolve(false); return; } transition('checking', { reason: 'open-start' }); let settled = false; const fallback = (reason, error) => { if (settled) return; settled = true; transition(error?.name === 'QuotaExceededError' ? 'quota-exceeded' : 'temporary', { reason, error }); resolve(false); }; const timer = setTimeout(() => fallback('open-timeout'), timeoutMs); const request = indexedDB.open(DATABASE_NAME, DATABASE_VERSION); request.onupgradeneeded = () => ensureStores(request.result); request.onblocked = () => { channel?.postMessage({ type: 'release-for-upgrade', targetVersion: DATABASE_VERSION, tabSessionId: sessionId }); fallback('upgrade-blocked'); }; request.onerror = () => { clearTimeout(timer); if (!settled) { settled = true; const error = request.error || new Error('IndexedDB open failed'); transition(error.name === 'QuotaExceededError' ? 'quota-exceeded' : 'failed', { reason: 'open-error', error }); reject(error); } }; request.onsuccess = async () => { clearTimeout(timer); if (settled) return; settled = true; try { database = attach(request.result); await mergeMemory(); transition('durable', { reason: 'open-complete' }); resolve(true); } catch (error) { transition('failed', { reason: 'recovery-merge', error }); reject(error); } }; }).finally(() => { openPromise = null; }); return openPromise; }
function put(name, item) { const value = { ...item, updatedAt: item.updatedAt || Date.now() }; if (!database) { memoryStore(name).set(value.id, value); return Promise.resolve(value); } return result(database.transaction(name, 'readwrite').objectStore(name).put(value)).catch((error) => { transition(error.name === 'QuotaExceededError' ? 'quota-exceeded' : 'failed', { reason: 'write-error', error }); throw error; }); }
function get(name, id) { return database ? result(database.transaction(name).objectStore(name).get(id)) : Promise.resolve(memoryStore(name).get(id)); }
function all(name) { return database ? result(database.transaction(name).objectStore(name).getAll()) : Promise.resolve([...memoryStore(name).values()]); }
function remove(name, id) { if (!database) { memoryStore(name).delete(id); return Promise.resolve(); } return result(database.transaction(name, 'readwrite').objectStore(name).delete(id)); }
function putMany(recordsByStore, removals = {}) { const names = [...new Set([...Object.keys(recordsByStore), ...Object.keys(removals)])]; if (!database) { for (const name of names) { for (const id of removals[name] || []) memoryStore(name).delete(id); for (const record of recordsByStore[name] || []) { const value = { ...record, updatedAt: record.updatedAt || Date.now() }; memoryStore(name).set(value.id, value); } } return Promise.resolve(); } const tx = database.transaction(names, 'readwrite'); for (const name of names) { for (const id of removals[name] || []) tx.objectStore(name).delete(id); for (const record of recordsByStore[name] || []) tx.objectStore(name).put({ ...record, updatedAt: record.updatedAt || Date.now() }); } return whenComplete(tx).catch((error) => { transition(error?.name === 'QuotaExceededError' ? 'quota-exceeded' : 'failed', { reason: 'batch-write-error', error }); throw error; }); }
function clearAll() { return Promise.all(STORES.map((name) => database ? result(database.transaction(name, 'readwrite').objectStore(name).clear()) : Promise.resolve(memoryStore(name).clear()))); }
function migrationPlan(fromVersion = 0) { return fromVersion < DATABASE_VERSION ? [{ version: DATABASE_VERSION, risk: 'additive', description: 'Ensure all local-first stores, including outbox, exist.' }] : []; }
async function enqueueOutbox(operation) { if (!operation?.id) throw new TypeError('Outbox operations require a stable id.'); const existing = await get('outbox', operation.id); if (existing) return existing; return put('outbox', { ...operation, status: operation.status || 'queued', retryCount: Number(operation.retryCount || 0), createdAt: operation.createdAt || new Date().toISOString(), updatedAt: operation.updatedAt || Date.now(), conflictState: operation.conflictState || null }); }
async function updateOutbox(id, patch) { const existing = await get('outbox', id); if (!existing) throw new Error(`Unknown outbox operation: ${id}`); return put('outbox', { ...existing, ...patch, id, updatedAt: Date.now() }); }
async function createPreMigrationBackup(details = {}) { const stores = {}; for (const name of STORES) { try { stores[name] = await all(name); } catch { stores[name] = []; } } return new Blob([JSON.stringify({ format: 'walk-wildlife-indexeddb-backup', version: 2, exportedAt: new Date().toISOString(), migration: details, database: DATABASE_NAME, databaseVersion: database?.version || 0, stores })], { type: 'application/json' }); }
function diagnostics() { return { state, databaseName: DATABASE_NAME, currentVersion: database?.version || 0, targetVersion: DATABASE_VERSION, sessionId, memoryRecords: [...memoryStores.values()].reduce((total, records) => total + records.size, 0), transitions: [...transitions] }; }
if (typeof window !== 'undefined') { window.addEventListener('pagehide', () => { database?.close(); database = null; }); window.addEventListener('visibilitychange', () => { if (document.visibilityState === 'hidden') channel?.postMessage({ type: 'heartbeat', tabSessionId: sessionId, at: Date.now() }); }); }
channel?.addEventListener('message', (event) => { if (event.data?.type === 'release-for-upgrade' && database) { database.close(); database = null; } });
// The loader may request a user-controlled backup before future risky migrations.
const beforeRiskyMigration = true;
export const db = { open, put, putMany, get, all, remove, clearAll, migrationPlan, enqueueOutbox, updateOutbox, createPreMigrationBackup, beforeRiskyMigration, version: DATABASE_VERSION, databaseName: DATABASE_NAME, sessionId, diagnostics, isDurable: () => Boolean(database), persistenceState: () => state, onPersistenceState: (listener) => { listeners.add(listener); return () => listeners.delete(listener); } };
export default db;
