def summarize(ledger):
    sources=list(ledger.sources.values()); events=[e for s in sources for e in s.events if not e.expired]
    domains={s.canonical_domain for s in sources}; regions={s.geography_id for s in sources}
    attempts=len(ledger.attempts); current=len(events)
    package_counts={status: sum(item.get("status") == status for item in getattr(ledger, "review_packages", [])) for status in ("READY FOR REVIEW", "APPROVED", "PROMOTED")}
    package_gaps=sorted({gap for report in getattr(ledger, "coverage", []) for gap in report.get("gaps", [])})
    accepted=sum(report.get("recordCount", 0) - report.get("duplicateCount", 0) for report in getattr(ledger, "coverage", []))
    rejected=sum(len(report.get("validationErrors", [])) for report in getattr(ledger, "coverage", []))
    return {"window":"ledger lifetime unless run_id/as_of filter is supplied","new_poi_records":len(getattr(ledger, "pois", [])),"package_counts":package_counts,"package_coverage_gaps":package_gaps,"package_accepted_records":accepted,"package_rejected_records":rejected,"regions_searched":len(regions),"new_canonical_domains":len(domains),"new_publishers":len({s.publisher_id for s in sources if s.publisher_id}),"current_event_yield":current,"geocoded_event_coverage":sum(e.latitude is not None and e.longitude is not None for e in events)/current if current else None,"freshness":"known from event validation timestamps; no data" if not events else "validated current events","fallback_success_rate":sum(bool(a["produced_events"]) for a in ledger.attempts)/attempts if attempts else None,"adapter_success_rate":sum(a.get("result") in ("succeeded","succeeded with events") for a in ledger.attempts)/attempts if attempts else None,"migration_recoveries":sum(s.status.value=="SOURCE MIGRATED" for s in sources),"duplicate_sources":sum(s.status.value=="DUPLICATE SOURCE" for s in sources),"loop_exclusions":sum(1 for d in ledger.decisions if d.get("score",{}).get("loop_penalty",0)>0),"empty_calendars":sum(s.status.value=="NO CURRENT EVENTS" for s in sources),"promotion_ready_sources":sum(s.status.value=="READY FOR REVIEW" for s in sources),"next_recommended_acquisition_batch":[d["geography_id"] for d in ledger.decisions[-3:]],"reasons":[d["reason"] for d in ledger.decisions[-3:]]}
